services:
    wordpress:
        image: wordpress:latest
        container_name: wordpress
        volumes:
            - ./wp-content:/var/www/html/wp-content
        environment:
            - WORDPRESS_DB_NAME=wp-test
            - WORDPRESS_TABLE_PREFIX=wp_
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_USER=wordpress
            - WORDPRESS_DB_PASSWORD=111222333444555
        depends_on:
            - db
            - phpmyadmin
        restart: always
        ports:
            - 8080:80

    db:
        image: mariadb:latest
        container_name: db
        volumes:
            - db_data:/var/lib/mysql
            # This is optional!!!
            - ./wp-content/dump.sql:/docker-entrypoint-initdb.d/dump.sql
            # # #
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=111222333444555
            - MYSQL_DATABASE=wp-test
        restart: always

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        ports:
            - 8180:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password

volumes:
    db_data:
